export const AppRoutes = {
  home: "/",
  testing: "/testing",
  login: "/login",
  scoringRules: "/scoring-rules",
  decisionRules: "/decision-rules",
  addScoringRule: "/scoring-rules/new-rule",
  viewScoringRule: "/scoring-rules/view-rule",
  editScoringRule: "/scoring-rules/edit-rule",
  addDecisionRule: "/decision-rules/new-rule",
  viewDecisionRule: "/decision-rules/view-rule",
  editDecisionRule: "/decision-rules/edit-rule",
  events: "/events",
  systemConfiguration: "/system-configuration",
  monitoring: "/monitoring",
  monitoringView: "/monitoring/view",
  organizations: "/organizations",
  users: "/users",
  analytics: "/analytics",
  myAccount: "/my-account",
  aboutUs: "/about-us",
  support: "/support",
  customerProfile : "/customer-profile",
};
