export const AppRoutes = {
  home: "/",
  testing: "/testing",
  login: "/login",
  rules: "/rules",
  addRule: "/rules/add",
  viewRule: "/rules/view",
  editRule: "/rules/edit",
  events: "/events",
  systemConfiguration: "/system-configuration",
  monitoring: "/monitoring",
  organizations: "/organizations",
  users: "/users",
  analytics: "/analytics",
  myAccount: "/my-account",
  aboutUs: "/about-us",
  support: "/support",
};
